### ISSUE TITLE
Suggestion - set the font-family once

### ISSUE THREAD

**Issue by jzhu01** [ssmythe/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/ssmythe/prj-rev-bwfs-dasmoto/blob/83eb4467e75366e7b8ab2087f8d9992e0fa5de1c/resources/css/styles.css#L3

I recommend setting the font-family once using a body or universal selector to avoid repetition! :)

**Comment by ssmythe** [comment]
Keeping code DRY.  Always a good thing!  :-D  Thanks for the tip.
